### ISSUE TITLE
support `using: node20` per github actions transition, and to support ng cli v17+

### ISSUE THREAD

**Issue by AndyAtTib** [ItzRabbs/ng-update#894]
Is it possible to update the actions.yml to support the node20 runner?

- Per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

    > Node 16 has reached its end of life, prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. 

- Per https://angular.dev/reference/versions, ng versions 17 and 18 require a minimum of node v18

At the moment, running the action gives the warning:

> The following actions use a deprecated Node.js version and will be forced to run on node20: fast-facts/ng-update@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by fast-facts** [comment]
Updated. No need to change anything in your workflow, I kept the version the same.
